apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deprecated-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deprecated-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        matchLabels:
          app: deprecated-nginx
